# Generated by Django 5.0.1 on 2024-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('uczeń', 'Student'), ('nauczyciel', 'Teacher')], default=('uczeń', 'Student'), max_length=20, verbose_name='Typ'),
        ),
    ]
