# Generated by Django 4.2.5 on 2023-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customgroup_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Kid', 'Dziecko'), ('Parent', 'Rodzic'), ('Admin', 'Administrator'), ('Moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
