# Generated by Django 4.2.5 on 2023-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_child_parent_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='role',
            field=models.CharField(default='Dziecko', max_length=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='role',
            field=models.CharField(default='Rodzic', max_length=20),
        ),
    ]
