# Generated by Django 5.0.1 on 2024-01-24 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_classrooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, to='tests.exercise'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='members',
            field=models.ManyToManyField(related_name='created_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
