# Generated by Django 5.0.1 on 2024-01-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_classroom_created_by_alter_classroom_exercises_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='users',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
