# Generated by Django 5.0.1 on 2024-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_rename_users_classroom_members_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='tests.exercise'),
        ),
    ]
